spring:
  datasource:
      url: jdbc:sqlserver://enviroment-parameters-dbadmin.database.windows.net:1433;database=SurroundingConditions;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
      password: ${DBPASS:}
      username: ${DBUSER:}

  jpa:
    database-platform: org.hibernate.dialect.SQLServer2008Dialect
